### ISSUE TITLE
Adobe Link Certificate Processing error

### ISSUE THREAD

**Issue by maxwellfunk** [GSA/playbooks-wdsv2#228]
#### Description of Issue: ####
Adobe reader and Adobe DC/standard are not able to process link cerificates as part of the common G2 migration

#### Possible Solution ####
Adobe is going to update their software to allow the processing of link certificates; however, registry changes on a users machine will be necessary to allow appropriate processing.

#### If a New Page or Content is Needed, Expected Outcomes: ####
New instructions on the issue and registry key changes need to be added to the Common G2 migration guide

**Comment by techliaison** [comment]
The registry setting requirement is temporary - so instead of
Adobe is going to update their software to allow the processing of link certificates; however, registry changes on a users machine will be necessary to allow appropriate processing.
it should read
Adobe is going to update their software to allow the processing of link certificates; however, until that update is released a registry setting on a user's machine can turn on the patch to allow appropriate processing.

**Comment by maxwellfunk** [comment]
adobe pushed a fix to their software that incorporates the registry changes needed to process link certificates.  Instructions backed up to shared drive and branch deleted.  closing issue.
