### ISSUE TITLE
Update FPKI CA References

### ISSUE THREAD

**Issue by idmken** [GSA/playbooks-wdsv2#509]
It would be helpful if the FPKI CA category table listed or linked to examples.

https://playbooks.idmanagement.gov/fpki/ca/#all-federal-pki-certification-authorities

PKI SSP should link to the government identities list - https://www.idmanagement.gov/buy/trust-services/#government-identity-services

Private sector should link to business identities list - https://www.idmanagement.gov/buy/trust-services/#business-identity-services

Bridge cas should link to non-gov trust frameworks list - https://www.idmanagement.gov/buy/trust-services/#non-government-pki-trust-framework

Federal agency legacy - include which agencies are federal legacy with active certificates (DoD, State, Treasury, PTO, and GPO.) Verify this list with someone on FPKI Team. There are other legacy but do not have active certs. Only include those with active certs.

**Comment by maxwellfunk** [comment]
For Federal agency legacy, that list would only really include DoD, State, PTO and GPO (all of which have active certs, but GPO plans to shut down their CAs by end of 2023).... Treasury is a full active and compliant SSP and would not be considered legacy.

We do have a list of all PIV/PIV-I issuing CAs that we could link to; however, there is not a 1:1 mapping 
 - for SSPs there is Entrust, Treasury, DigiCert, Verizon, and Widepoint/ORC
 - 4 bridges - CertiPath, TSCP, STRAC, SAFE
 - for business there are several NFIs that are also SSPs and some of which bridge members (as opposed to bridge providers)
 
As a result it is difficult to provide a 1:1 linking.

**Comment by claytonjbarnette** [comment]
@idmken Let me know how you want me to proceed with this one.

**Comment by idmken** [comment]
@maxwellfunk, what is the intent of categorizing different CAs on this page? This table seems abstract because the categories aren't used anywhere else. I checked common policy and federal bridge, and federal legacy isn't mentioned in the document except in the common change table. If there's no reason to categorize, I'll align this to the trust services page.

**Comment by maxwellfunk** [comment]
@idmken this is very abstract and probably from years before you or I were ever associated with the FPKI.  I'm sure this was a high level conceptual diagram/table to roughly categorize CAs into buckets that could be easily briefed to senior leadership and make it look like FPKI is helio-centric in the solar system of PKI.  Since then we obviously have a more granular view of the CAs throughout FPKI (think trust monitor) but that is not user friendly. 

Linking these to trust services is probably fine for ease of navigation, as mentioned there will be strange exceptions to a 1:1 mapping, but I don't think it will impact anyone looking at the page.
