### ISSUE TITLE
Update Site to Ruby 3

### ISSUE THREAD

**Issue by idmken** [GSA/playbooks-wdsv2#739]
Currently on Ruby 2.7.5. Research how to upgrade to latest Ruby 3 and its impact.

I think there is a dependency with our Ruby version, Jekyll, and Cloud.gov pages.

**Comment by idmken** [comment]
Ruby 2.7.5 is in security maintenance with EOL coming soon.

https://www.ruby-lang.org/en/downloads/

**Comment by claytonjbarnette** [comment]
This issue was addressed in: [#365 on IDManagement.gov](https://github.com/GSA/idmanagement.gov/pull/365) using a combination of the two resources below: 

**Resources :** 
- [https://github.com/cloud-gov/pages-uswds-jekyll](https://github.com/cloud-gov/pages-uswds-jekyll)
- [https://cloud.gov/2023/05/24/cloud-gov-pages-jekyll-ruby-upgrade/](https://cloud.gov/2023/05/24/cloud-gov-pages-jekyll-ruby-upgrade/)

Additional information can be found in the issue below about the move of Playbooks to IDManagement.gov.
- [https://github.com/GSA/ficam-playbooks/issues/953](https://github.com/GSA/ficam-playbooks/issues/953)

@SuGhadiali
